apiVersion: batch/v1
kind: Job
metadata:
  name: url-to-video
spec:
  template:
    spec:
      containers:
        - name: url-to-video
          image: cipheredbytes/url-to-video
          volumeMounts:
            - name: recordings
              mountPath: /recordings/
      env:
        - name: URL
          value: "https://www.youtube.com/watch?v=PBYKqvDK8d8"
        - name: DURATION
          value: "20"
        - name: OUTPUT_FILENAME
          value: "forever_tracey.mp4"
      restartPolicy: Never
      volumes:
        - name: recordings
          persistentVolumeClaim:
          claimName: recordings-pv-claim
  backoffLimit: 2
